name: Aggregate Documentation

on:
  workflow_dispatch:

concurrency:
  group: aggregate-opengeometry-docs
  cancel-in-progress: true

jobs:
  aggregate-docs:
    runs-on: ubuntu-latest
    name: Aggregate mintlify docs
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Run mintlify action
        uses: mintlify/mintlify-multirepo-action@v0.15
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          target-branch: docs
          subdirectory: .

          repos: |
            - owner: OpenGeometry-io
              repo: OpenGeometry
              subdirectory: docs
              prefix: opengeometry

            - owner: OpenGeometry-io
              repo: OpenPlans
              subdirectory: docs
              prefix: openplans
